services:
  ubuntu-dind:
    image: ubuntu:22.04
    container_name: ubuntu-dind
    privileged: true
    restart: always
    command: ["/bin/bash", "-c", "chmod +x /setup/setup.sh && /setup/setup.sh"]
    networks:
      - ubuntu_network
    volumes:
      - ubuntu_docker:/var/lib/docker
      - ./setup:/setup
      - ./.env:/setup/.env
    build:
      context: .
      dockerfile: Dockerfile

  postgres:
    image: postgres:16
    container_name: ubuntu-postgres
    restart: always
    environment:
      POSTGRES_USER: "${PG_USERNAME}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_DB: "${PG_DATABASE_NAME}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:5432"
    networks:
      - ubuntu_network
    depends_on:
      - ubuntu-dind

  redis:
    image: redis:latest
    container_name: ubuntu-redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - ubuntu_network
    depends_on:
      - ubuntu-dind

networks:
  ubuntu_network:
    driver: bridge

volumes:
  ubuntu_docker:
  postgres_data: